CREATE TABLE IF NOT EXISTS rol (
id INT NOT NULL AUTO_INCREMENT,
nombre VARCHAR(15) NOT NULL,
PRIMARY KEY (id),
UNIQUE KEY (nombre)
);

INSERT IGNORE INTO rol (id,nombre) VALUES
(1,"ROL_PROFESOR"),
(2,"ROL_ESTUDIANTE");


CREATE TABLE IF NOT EXISTS curso (
id INT NOT NULL AUTO_INCREMENT,
nombre VARCHAR(1) NOT NULL,
PRIMARY KEY (id),
UNIQUE KEY (nombre)
);

INSERT IGNORE INTO rol (id,nombre) VALUES
(1,"A"),
(2,"B"),
(3,"C");

-- "$10$SeF/ssj0ROeXxEJM7S2Yceipu/Qa4bchiZBTI3jw7J7kWZfhlKmwC"